release:
  github:
    owner: duck8823
    name: duci
builds:
  - binary: duci
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w -X github.com/duck8823/duci/application.version={{.Version}} -X github.com/duck8823/duci/application.revesion={{.Commit}}
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
