---
dataSource: "prs"
groupBy:
  "Enhancements:":
    - "enhancement"
    - "internal"
  "Bug Fixes:":
    - "bug"
  "Update Dependencies:":
    - "dependencies"
  "Maintenances:":
    - "maintenance"
template:
  label: ""