---
version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "live"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "live"
  - package_manager: "docker"
    directory: "/.duci"
    update_schedule: "live"
