on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
name: deploy
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: smoke-test
        run: go run main.go run
      - uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
