on: push
name: main workflow
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: lint
      uses: docker://golangci/golangci-lint:latest
      with:
        entrypoint: golangci-lint
        args: run --disable-all --enable=gofmt --enable=vet --enable=gocyclo --enable=golint
          --enable=ineffassign --enable=misspell --deadline=5m
    - name: tidy
      uses: docker://golang:1.12
      env:
        GOPATH: /github/workspace/.go
      with:
        entrypoint: go
        args: mod tidy
    - name: download
      uses: docker://golang:1.12
      env:
        GOPATH: /github/workspace/.go
      with:
        entrypoint: go
        args: mod download
    - name: check modified
      uses: docker://alpine/git:latest
      with:
        entrypoint: sh
        args: -c "! git status | grep modified"
    - name: test
      uses: docker://golang:1.12
      env:
        GOPATH: /github/workspace/.go
      with:
        entrypoint: go
        args: test ./...
