on: push
name: test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: docker://golangci/golangci-lint:v1.36
        with:
          entrypoint: make
          args: lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: docker://golang:1.13
        with:
          entrypoint: make
          args: test
  duci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: duck8823/duci@master
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: smoke-test
        run: go run main.go run