on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dependabot/**
  push:
    paths:
      - .github/workflows/tidy-modules.yml

name: tidy modules

jobs:
  tidy-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16.1
      - run: go version
      - name: check modified
        run: echo "::set-output name=EXIT_STATUS::$(git status | grep modified >/dev/null; echo $?)"
        id: check-modified
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add -A
          git commit -m "go mod tidy"
          git push origin HEAD:${{ github.head_ref }}
        if: ${{ steps.check-modified.outputs.EXIT_STATUS == 0 }}